[build]
publish = "public"
command = "npm i -g postcss-cli autoprefixer; hugo --enableGitInfo --buildFuture -b $URL"

[context.production.environment]
HUGO_VERSION = "0.49.2"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
