---
title: "Machine Learning with Tibbles"
date: 2018-10-21T15:43:48+08:00
lastmod: 2018-08-31T15:43:48+08:00
author: "Chris Stroud"
output:
  blogdown::html_page:
    toc: true

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

# Objective

The purpose of this blah blah


```{r load, message=FALSE, warning=FALSE, paged.print=FALSE}
##############################
# - Load librairies
##############################
library(dplyr)
library(ggplot2)
library(plotly)
library(gapminder)
library(knitr)
library(kableExtra)


library(RCurl)
myfile <- getURL('https://sakai.unc.edu/access/content/group/3d1eb92e-7848-4f55-90c3-7c72a54e7e43/public/data/bycatch.csv', ssl.verifyhost=FALSE, ssl.verifypeer=FALSE)

df <- read.csv(textConnection(myfile), header=T)


```

## two column testing


```{r load2, message=FALSE, warning=FALSE}
df %>% 
	group_by(Season) %>% 
	summarise(test = mean(Tows)) %>% 
	kable 
```




```{r load4, message=FALSE, warning=FALSE}
df %>% 
	kable 
```



```{r load3, message=FALSE, warning=FALSE, out.width = "100%"}
df %>% 
	group_by(Season) %>% 
	summarise(test = mean(Tows)) %>% 
	ggplot(aes(x=Season, y =test)) + 
	geom_point(size = 5) + 
	theme_light() +
	theme(panel.background = element_rect(fill="#FFFCF7")) +
	theme(plot.background = element_rect(fill = "#FFFCF7"))

```






